# Generated by Django 5.2.13 on 2026-04-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0016_auto_20260409_1943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(default='sample'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='temp_field',
            field=models.CharField(default='temp', max_length=10),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title',
            field=models.CharField(default='sample', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
