# Generated by Django 5.2.13 on 2026-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0017_workshop_description_workshop_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='temp_field',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
